### ISSUE TITLE
Colorful.Console Dictionary Exception

### ISSUE THREAD

**Issue by zolrath** [tomakita/Colorful.Console#4]
I've been using Colorful.Console for a test application and in a multi-threaded environment the ColorStore causes an exception. The Color is getting added to the dictionary in another thread, making the colorStore.RequiresUpdate check invalid.

`Console.WriteLine("Setting initial behavior to stopped", Color.Cyan);`
ends up throwing an Exception as it seems to be attempting to add the Color to a dictionary in which it already exists.

 ```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Colorful.ColorStore.Update(Color newColor, ConsoleColor oldColor)
   at Colorful.ColorManager.GetConsoleColor(Color color)
   at Colorful.Console.WriteInColor[T](Action`1 action, T target, Color color)
   at Colorful.Console.WriteLine(String value, Color color)
```

This can be fixed by either switching to ConcurrentDictionary or catching the exception in ColorStore.Update.

**Comment by tomakita** [comment]
Thanks for reporting this, Matt, and thanks for the contributing the fix!
