### ISSUE TITLE
The handle is invalid.

### ISSUE THREAD

**Issue by grounzero** [tomakita/Colorful.Console#73]
Got this error when running `Nuke.GlobalTool ` that references this repo and was told to raise a bug here.

```
The handle is invalid.
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.set_CursorLeft(Int32 value)
   at Colorful.Console.set_CursorLeft(Int32 value)
```
More info here

https://github.com/nuke-build/nuke/issues/423

**Comment by grounzero** [comment]
Additional info: I notice this seems to happen when using https://conemu.github.io/ 

Using cmd.exe I do not see this exception.

**Comment by Sonic3R** [comment]
Yes it happens if console is launched without window visibilty ... It occur at Console.Clear or Console.CursorLeft/CursorTop because there's no allocated buffer for writing to display
