### ISSUE TITLE
alignment of text

### ISSUE THREAD

**Issue by thebuilderNL** [tomakita/Colorful.Console#9]
wouldn't it be handy if we can align text in console?

**Comment by tomakita** [comment]
Hi,

Would it be possible to give some examples of what you mean?

Thanks!

**Comment by thebuilderNL** [comment]
like Console.WriteLineAligned("hello World!",Color.Red,Align.Center);
then it would align to center, so the text would be in the middle of the window.
i would like to use this feature with acsii.

**Comment by codepunkt** [comment]
I'm interested. This would be a welcome addition! 👍

**Comment by tomakita** [comment]
Thanks for the feedback.  I've planned to add alignment as a part of another feature which I'm working on at the moment.  Unfortunately, I don't have an ETA, but I will update this thread when I get closer to release!

**Comment by xxcanizeusxx** [comment]
For those looking for a simple solution this enables you to write to the console at any position you wish. However, this does not work with the library's ACSII method. Everything moves tot he x and y postion but the top of the ASCII dashes are out of order. If you want plain text this works everywhere in the console window. Please ignore my typewritter function. This function just adds a nice old school sound effect.

`  public class Screen
    {
        
        private const int delay = 300;
        private static int _leftPos;
        private static int _topPos;

        public Screen(int leftPos, int topPos, int screenWidth, int screenHeight)
        {
            _leftPos = leftPos;
            _topPos = topPos;
            SetUpScreen(screenWidth, screenHeight);
        }

        private static void SetUpScreen(int width, int height)
        {
            IntPtr ptr = GetConsoleWindow();
            MoveWindow(ptr, 0, 0, 1000, 400, true);
            Console.SetWindowSize(width, height);
        }

        public void WriteAt(string message, int x, int y, bool typeWritter, bool newLine)
        {
            try
            {
                Console.SetCursorPosition(_leftPos + x, _topPos + y);
                if(typeWritter && message != null)
                {
                    TypeWritter(message, delay, newLine);
                }
            }
            catch(ArgumentOutOfRangeException e)
            {
                Console.Clear();
                Console.Beep(37, 500);
                Console.Write(e.Message);
            }
        }

        public void TypeWritter(string message, int delay, bool newLine)
        {
            var player = new SoundPlayer
            {
                SoundLocation = @"C:\Users\Erick\Desktop\C#\CanizHospital\CanizHospital\typewriter-key-1.wav"
            };
            foreach (char c in message)
            {
                player.Play();
                Console.Write(c);
                Thread.Sleep(delay);
                player.Stop();
            }
            if (newLine)
            {
                Console.Write(Environment.NewLine);
                player.SoundLocation = @"C:\Users\Erick\Desktop\C#\CanizHospital\CanizHospital\typewriter-return-1.wav";
                player.PlaySync();
                //Thread.Sleep(delay); // Might not be necessary
            }
        }

        [DllImport("kernel32.dll", SetLastError = true)]
        static extern IntPtr GetConsoleWindow();

        [DllImport("user32.dll", SetLastError = true)]
        internal static extern bool MoveWindow(IntPtr hWnd, int X, int Y, int nWidth, int nHeight, bool bRepaint);
    }`

**Comment by wangshuai-007** [comment]
from msdn:[Composite formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting?redirectedfrom=MSDN#alignment-component),I can write line with alignment in consol like this:
```c#
Console.WriteLine($"  {123,-10}{"--123",-10}")
Console.WriteLine($"  {123456,-10}{"--123",-10}")
```
And in `Colorful.Console`,it is also worked.
```c#
Colorful.Console.WriteLine($"  {123,-10}{"--123",-10}")
Colorful.Console.WriteLine($"  {123456,-10}{"--123",-10}")
```
But,when I use this Code
```c#
Colorful.Console.WriteLineFormatted("  {0,-10}--{1,-10}",Color.White,new Colorful.Formatter[]{new Colorful.Formatter(123,Color.Red),new Colorful.Formatter("--123",Color.Aqua)});

```
,I will get error:
```c#
異常信息：
Input string was not in a correct format.

调用堆栈:
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at Colorful.TextFormatter.GetFormatMap(String input, Object[] args, Color[] colors)
   at Colorful.Console.WriteInColorFormatted[T](String trailer, T target0, Formatter[] targets, Color defaultColor)
   at Colorful.Console.WriteLineFormatted(String format, Color defaultColor, Formatter[] args)

```
can the Colorful.Console support Alignment ?

**Comment by Jirubizu** [comment]
Has this been resolved? I still can't use alignments with formatted texts

**Comment by neila-a** [comment]
> from msdn:[Composite formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting?redirectedfrom=MSDN#alignment-component),I can write line with alignment in consol like this:
> 
> ```cs
> Console.WriteLine($"  {123,-10}{"--123",-10}")
> Console.WriteLine($"  {123456,-10}{"--123",-10}")
> ```
> 
> And in `Colorful.Console`,it is also worked.
> 
> ```cs
> Colorful.Console.WriteLine($"  {123,-10}{"--123",-10}")
> Colorful.Console.WriteLine($"  {123456,-10}{"--123",-10}")
> ```
> 
> But,when I use this Code
> 
> ```cs
> Colorful.Console.WriteLineFormatted("  {0,-10}--{1,-10}",Color.White,new Colorful.Formatter[]{new Colorful.Formatter(123,Color.Red),new Colorful.Formatter("--123",Color.Aqua)});
> ```
> 
> ,I will get error:
> 
> ```cs
> 異常信息：
> Input string was not in a correct format.
> 
> 调用堆栈:
>    at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>    at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
>    at System.Int32.Parse(String s)
>    at Colorful.TextFormatter.GetFormatMap(String input, Object[] args, Color[] colors)
>    at Colorful.Console.WriteInColorFormatted[T](String trailer, T target0, Formatter[] targets, Color defaultColor)
>    at Colorful.Console.WriteLineFormatted(String format, Color defaultColor, Formatter[] args)
> ```
> 
> can the Colorful.Console support Alignment ?

I think this means that Colorful.Console doesn't conflict with alignment under the hood, just (probably) due to some matching errors.
